//! Emit Kodi-format NFO files next to user media.
//!
//! Every NFO we write carries an XML-comment marker that embeds a short
//! SHA-256 fingerprint of the body. On a later run, [`marker_status`] reads
//! that fingerprint and reports whether the file is:
//!
//! - missing the marker (a foreign file from another tool, or hand-written),
//! - marked and unchanged since we last wrote it, or
//! - marked but the body now differs (user edited it after we wrote it).
//!
//! Writes are atomic: render to `<path>.pacefinder-tmp`, then `rename` to
//! `<path>`. Survives Ctrl-C without leaving truncated files behind.

use anyhow::{Context, Result};
use sha2::{Digest, Sha256};
use std::fs;
use std::io::Read;
use std::path::Path;
use tracing::debug;

use super::kodi::{KodiEpisode, KodiSeason, KodiTvShow};
use crate::model::{Episode, Season, Series};

const XML_DECL: &str = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n";

/// Anchor for marker detection. The leading `<!--` keeps the prefix from
/// matching arbitrary prose elsewhere in a foreign NFO.
const MARKER_OPEN: &str = "<!-- generated by pacefinder/";
const MARKER_CLOSE: &str = "-->\n";

/// First-N hex chars of sha256(body) embedded in the marker. 64-bit prefix
/// is enough that collisions between distinct bodies are not a concern.
const HASH_HEX_LEN: usize = 16;

pub fn write_series(path: &Path, series: &Series, lock: bool) -> Result<()> {
    let mut kodi: KodiTvShow = series.clone().into();
    kodi.lockdata = lock.then_some(true);
    write_xml(path, &kodi, "tvshow")
}

pub fn write_season(path: &Path, season: &Season, lock: bool) -> Result<()> {
    let mut kodi: KodiSeason = season.clone().into();
    kodi.lockdata = lock.then_some(true);
    write_xml(path, &kodi, "season")
}

pub fn write_episode(path: &Path, episode: &Episode, lock: bool) -> Result<()> {
    let mut kodi: KodiEpisode = episode.clone().into();
    kodi.lockdata = lock.then_some(true);
    write_xml(path, &kodi, "episodedetails")
}

fn write_xml<T: serde::Serialize>(path: &Path, value: &T, root: &str) -> Result<()> {
    let body = quick_xml::se::to_string_with_root(root, value)
        .with_context(|| format!("serializing <{root}>"))?;
    let body_with_trailing = format!("{body}\n");
    let hash = body_hash(&body_with_trailing);
    let marker = format!(
        "{MARKER_OPEN}{ver} sha256:{hash} {MARKER_CLOSE}",
        ver = env!("CARGO_PKG_VERSION"),
    );
    let out = format!("{XML_DECL}{marker}{body_with_trailing}");
    atomic_write(path, out.as_bytes())?;
    debug!(path = %path.display(), "wrote nfo");
    Ok(())
}

/// Atomic write: render to a sibling temp file, then rename. `rename` on
/// the same filesystem is atomic on POSIX and on NTFS via Win32. Falls
/// back to the temp file on error so the original is never half-written.
fn atomic_write(path: &Path, bytes: &[u8]) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    let tmp = tmp_path_for(path);
    fs::write(&tmp, bytes).with_context(|| format!("writing tmp {}", tmp.display()))?;
    fs::rename(&tmp, path)
        .with_context(|| format!("renaming tmp -> {}", path.display()))
        .inspect_err(|_| {
            let _ = fs::remove_file(&tmp);
        })?;
    Ok(())
}

fn tmp_path_for(path: &Path) -> std::path::PathBuf {
    let mut buf = path.as_os_str().to_owned();
    buf.push(".pacefinder-tmp");
    buf.into()
}

fn body_hash(body: &str) -> String {
    let digest = Sha256::digest(body.as_bytes());
    let mut out = hex::encode(digest);
    out.truncate(HASH_HEX_LEN);
    out
}

/// Per-file classification result. See module docs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MarkerStatus {
    /// File has no pacefinder marker — either foreign or hand-written.
    Absent,
    /// Marker present and the embedded hash matches the current body.
    IntactOurs,
    /// Marker present but the body has been altered since we wrote it.
    EditedOurs,
}

/// Read the first ~512 bytes of `path` plus the rest of the body and
/// determine whether this file looks like pacefinder output.
pub fn marker_status(path: &Path) -> MarkerStatus {
    let Ok(mut file) = fs::File::open(path) else {
        return MarkerStatus::Absent;
    };
    // Read enough to cover the marker line generously. The marker itself is
    // ~60 chars; 512 leaves slack for an XML declaration variant.
    let mut head = String::new();
    if (&mut file).take(512).read_to_string(&mut head).is_err() {
        return MarkerStatus::Absent;
    }
    let Some(rest_start) = head.find(MARKER_OPEN) else {
        return MarkerStatus::Absent;
    };
    let marker_tail = &head[rest_start..];
    let Some(close_offset) = marker_tail.find(MARKER_CLOSE) else {
        return MarkerStatus::Absent;
    };
    let marker = &marker_tail[..close_offset];
    let Some(expected) = extract_hash(marker) else {
        return MarkerStatus::Absent;
    };

    // Everything in `head` after the marker is the start of the body. Read
    // any remaining bytes from the file too.
    let head_after_marker = &marker_tail[close_offset + MARKER_CLOSE.len()..];
    let mut body = head_after_marker.to_string();
    if file.read_to_string(&mut body).is_err() {
        return MarkerStatus::Absent;
    }
    let actual = body_hash(&body);
    if actual == expected {
        MarkerStatus::IntactOurs
    } else {
        MarkerStatus::EditedOurs
    }
}

fn extract_hash(marker: &str) -> Option<String> {
    // `marker` is e.g. "<!-- generated by pacefinder/0.1.0 sha256:abcdef0123456789 "
    // (trailing space before `-->` is stripped by find boundary)
    let after = marker.split_once("sha256:")?.1.trim();
    let hex: String = after.chars().take(HASH_HEX_LEN).collect();
    if hex.len() == HASH_HEX_LEN && hex.chars().all(|c| c.is_ascii_hexdigit()) {
        Some(hex)
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Episode, NamedSeason, Season, Series};
    use crate::nfo::kodi;
    use tempfile::tempdir;

    fn sample_series() -> Series {
        Series {
            title: "One Pace".into(),
            showtitle: "One Pace".into(),
            original_title: Some("One Piece".into()),
            plot: "Fan recut.".into(),
            display_order: Some("absolute".into()),
            named_seasons: vec![
                NamedSeason {
                    number: 1,
                    name: "1. Romance Dawn".into(),
                },
                NamedSeason {
                    number: 2,
                    name: "2. Orange Town".into(),
                },
            ],
        }
    }

    #[test]
    fn series_round_trips_through_disk() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("tvshow.nfo");
        let s = sample_series();
        write_series(&path, &s, false).unwrap();

        let xml = fs::read_to_string(&path).unwrap();
        let parsed: Series = kodi::parse_tvshow(&xml).unwrap().into();
        assert_eq!(parsed.title, s.title);
        assert_eq!(parsed.original_title, s.original_title);
        assert_eq!(parsed.named_seasons, s.named_seasons);
    }

    #[test]
    fn season_round_trips_through_disk() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("season.nfo");
        let s = Season {
            number: 1,
            title: "1. Romance Dawn".into(),
            plot: Some("Luffy sets out.".into()),
        };
        write_season(&path, &s, false).unwrap();
        let xml = fs::read_to_string(&path).unwrap();
        let parsed: Season = kodi::parse_season(&xml).unwrap().into();
        assert_eq!(parsed.number, 1);
        assert_eq!(parsed.title, s.title);
    }

    #[test]
    fn episode_round_trips_through_disk() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("ep.nfo");
        let e = Episode {
            showtitle: "One Pace".into(),
            season: 1,
            number: 1,
            title: "Romance Dawn, the Dawn of an Adventure".into(),
            plot: Some("Luffy meets Shanks.".into()),
            premiered: Some("2025-05-03".into()),
            aired: Some("2025-05-03".into()),
        };
        write_episode(&path, &e, false).unwrap();
        let xml = fs::read_to_string(&path).unwrap();
        let parsed: Episode = kodi::parse_episode(&xml).unwrap().into();
        assert_eq!(parsed.title, e.title);
        assert_eq!(parsed.season, 1);
        assert_eq!(parsed.number, 1);
        assert_eq!(parsed.aired, e.aired);
    }

    #[test]
    fn series_writes_lockdata_when_locked() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("tvshow.nfo");
        write_series(&path, &sample_series(), true).unwrap();
        let xml = fs::read_to_string(&path).unwrap();
        assert!(
            xml.contains("<lockdata>true</lockdata>"),
            "expected lockdata in:\n{xml}"
        );
    }

    #[test]
    fn series_omits_lockdata_when_unlocked() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("tvshow.nfo");
        write_series(&path, &sample_series(), false).unwrap();
        let xml = fs::read_to_string(&path).unwrap();
        assert!(
            !xml.contains("<lockdata>"),
            "unexpected lockdata in:\n{xml}"
        );
    }

    #[test]
    fn marker_intact_after_clean_write() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("tvshow.nfo");
        write_series(&path, &sample_series(), false).unwrap();
        assert_eq!(marker_status(&path), MarkerStatus::IntactOurs);
    }

    #[test]
    fn marker_edited_when_body_changed() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("tvshow.nfo");
        write_series(&path, &sample_series(), false).unwrap();
        // Hand-edit: append a stray comment to the body.
        let mut current = fs::read_to_string(&path).unwrap();
        current.push_str("<!-- user edit -->\n");
        fs::write(&path, current).unwrap();
        assert_eq!(marker_status(&path), MarkerStatus::EditedOurs);
    }

    #[test]
    fn marker_absent_for_foreign_nfo() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("foreign.nfo");
        fs::write(
            &path,
            "<?xml version=\"1.0\"?>\n<tvshow><title>Hand-edited</title></tvshow>\n",
        )
        .unwrap();
        assert_eq!(marker_status(&path), MarkerStatus::Absent);
    }

    #[test]
    fn marker_absent_for_missing_file() {
        let dir = tempdir().unwrap();
        assert_eq!(
            marker_status(&dir.path().join("nope.nfo")),
            MarkerStatus::Absent
        );
    }

    #[test]
    fn marker_absent_for_truncated_marker() {
        // A foreign file whose first 512 bytes do not contain the close `-->`
        // should be treated as Absent, not as garbled-ours.
        let dir = tempdir().unwrap();
        let path = dir.path().join("weird.nfo");
        let mut content = MARKER_OPEN.to_string();
        content.push_str("0.0.0 sha256:");
        content.push_str(&"x".repeat(1000)); // never closes; never includes -->
        fs::write(&path, content).unwrap();
        assert_eq!(marker_status(&path), MarkerStatus::Absent);
    }

    #[test]
    fn atomic_write_leaves_no_tmp_on_success() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("tvshow.nfo");
        write_series(&path, &sample_series(), false).unwrap();
        let entries: Vec<_> = fs::read_dir(dir.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name())
            .collect();
        assert_eq!(entries, vec!["tvshow.nfo"]);
    }
}
