//! `cleanup` subcommand: tidy up orphan arc folders left behind by other
//! tagging tools or by earlier matched-then-renamed pacefinder runs.
//!
//! Walks the immediate children of `<series-root>`. For each entry that
//! looks like an arc folder (per [`is_arc_folder_name`]) and does *not*
//! contain a pacefinder-managed `.nfo`:
//!
//! - empty folder → `rmdir`,
//! - non-empty folder → drop a small `.ignore` file so Jellyfin stops
//!   treating it as a season.
//!
//! Arc folders that hold at least one pacefinder-marked `.nfo` are left
//! alone — they're part of an active library. Foreign content lives
//! untouched; we only ever add `.ignore`, never delete media.
//!
//! Reverse with `--remove`, which deletes only the `.ignore` files whose
//! first line is `# generated by pacefinder`. User-authored `.ignore`
//! files are preserved.

use anyhow::{Context, Result};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use tracing::{info, warn};
use walkdir::WalkDir;

use crate::fs_util::canonicalize_root;
use crate::matcher::{
    ParsedFile, arc_from_folder_name, extended_folder_arc_ep, is_arc_folder_name, normalize_arc,
};
use crate::nfo::writer::{self, MarkerStatus};
use crate::scan::is_video;

const REPLACED_DIRNAME: &str = "_replaced";

/// First line of any `.ignore` we write. `--remove` keys on this prefix.
const IGNORE_MARKER: &str = "# generated by pacefinder";
const IGNORE_BODY: &str = "# generated by pacefinder\n\
                           # delete this file to make Jellyfin scan this folder again\n";
const IGNORE_FILENAME: &str = ".ignore";

pub struct Options {
    pub dry_run: bool,
    pub remove: bool,
    pub remove_superseded: bool,
    pub migrate_extended_folders: bool,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) enum Plan {
    Rmdir(PathBuf),
    WriteIgnore(PathBuf),
    Leave(PathBuf, &'static str),
}

pub fn run(root: &Path, opts: Options) -> Result<()> {
    let root = canonicalize_root(root)?;
    info!(
        path = %root.display(),
        dry_run = opts.dry_run,
        remove = opts.remove,
        remove_superseded = opts.remove_superseded,
        migrate_extended_folders = opts.migrate_extended_folders,
        "cleaning up arc folders",
    );

    if opts.remove {
        return run_remove(&root, opts.dry_run);
    }

    if opts.migrate_extended_folders {
        run_migrate_extended_folders(&root, opts.dry_run)?;
    }
    if opts.remove_superseded {
        run_remove_superseded(&root, opts.dry_run)?;
    }
    if opts.migrate_extended_folders || opts.remove_superseded {
        // Extended-specific work happens before (or instead of) the
        // arc-dir orphan scan; if either ran, we're done.
        return Ok(());
    }

    let arc_dirs = collect_arc_dirs(&root)?;
    let mut removed_dirs = 0usize;
    let mut wrote_ignore = 0usize;
    let mut left_matched = 0usize;
    let mut left_other = 0usize;
    let mut errored = 0usize;

    for dir in &arc_dirs {
        let plan = classify(dir);
        match apply(plan, opts.dry_run) {
            Ok(Outcome::Removed) => removed_dirs += 1,
            Ok(Outcome::WroteIgnore) => wrote_ignore += 1,
            Ok(Outcome::LeftMatched) => left_matched += 1,
            Ok(Outcome::LeftOther) => left_other += 1,
            Err(e) => {
                warn!(error = %e, "skipping {}", dir.display());
                errored += 1;
            }
        }
    }

    info!(
        removed_dirs,
        wrote_ignore,
        left_matched,
        left_other,
        errored,
        total = arc_dirs.len(),
        "cleanup complete",
    );

    if !opts.dry_run && (removed_dirs > 0 || wrote_ignore > 0) {
        info!(
            "After applying, trigger a Jellyfin library scan. If ghost seasons \
             persist, remove + re-add the library in Jellyfin's admin UI."
        );
    }
    Ok(())
}

fn run_remove(root: &Path, dry_run: bool) -> Result<()> {
    let arc_dirs = collect_arc_dirs(root)?;
    let mut removed = 0usize;
    let mut skipped_foreign = 0usize;
    let mut errored = 0usize;
    for dir in &arc_dirs {
        let ignore_path = dir.join(IGNORE_FILENAME);
        if !ignore_path.exists() {
            continue;
        }
        if !is_our_ignore(&ignore_path) {
            warn!(
                path = %ignore_path.display(),
                "leaving foreign `.ignore` (no pacefinder marker)"
            );
            skipped_foreign += 1;
            continue;
        }
        if dry_run {
            info!(would_remove = %ignore_path.display(), "[dry-run] remove .ignore");
            removed += 1;
            continue;
        }
        match fs::remove_file(&ignore_path) {
            Ok(()) => {
                info!(path = %ignore_path.display(), "removed .ignore");
                removed += 1;
            }
            Err(e) => {
                warn!(error = %e, "failed to remove {}", ignore_path.display());
                errored += 1;
            }
        }
    }
    info!(
        removed,
        skipped_foreign,
        errored,
        total = arc_dirs.len(),
        "cleanup --remove complete",
    );
    Ok(())
}

fn run_migrate_extended_folders(root: &Path, dry_run: bool) -> Result<()> {
    let arc_folders = list_arc_folders(root)?;
    let mut moved = 0usize;
    let mut skipped = 0usize;
    let mut errored = 0usize;
    for entry in fs::read_dir(root).with_context(|| format!("reading {}", root.display()))? {
        let entry = entry?;
        let path = entry.path();
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let Some((arc_name, _ep)) = extended_folder_arc_ep(name) else {
            continue;
        };
        let arc_norm = normalize_arc(&arc_name);
        let Some(parent_arc) = arc_folders.get(&arc_norm) else {
            warn!(
                pseudo_folder = %path.display(),
                arc = %arc_name,
                "no parent arc folder found; skipping (create the arc folder first or `download` it)",
            );
            skipped += 1;
            continue;
        };
        match migrate_one_extended_folder(&path, parent_arc, dry_run) {
            Ok(()) => moved += 1,
            Err(e) => {
                warn!(error = %e, "failed migrating {}", path.display());
                errored += 1;
            }
        }
    }
    info!(moved, skipped, errored, "migrate-extended-folders complete");
    Ok(())
}

fn list_arc_folders(root: &Path) -> Result<HashMap<String, PathBuf>> {
    let mut out = HashMap::new();
    for entry in fs::read_dir(root).with_context(|| format!("reading {}", root.display()))? {
        let entry = entry?;
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        // arc_from_folder_name returns None for non-arc shapes, so it
        // doubles as both the recognizer and the name extractor.
        if let Some(arc) = arc_from_folder_name(name) {
            out.insert(normalize_arc(&arc), path);
        }
    }
    Ok(out)
}

fn migrate_one_extended_folder(pseudo: &Path, parent_arc: &Path, dry_run: bool) -> Result<()> {
    let entries: Vec<PathBuf> = fs::read_dir(pseudo)
        .with_context(|| format!("reading {}", pseudo.display()))?
        .flatten()
        .map(|e| e.path())
        .collect();
    let mut moved_any = false;
    for src in &entries {
        let Some(name) = src.file_name() else {
            continue;
        };
        let dst = parent_arc.join(name);
        if dst.exists() {
            warn!(dst = %dst.display(), src = %src.display(), "destination exists; skipping");
            continue;
        }
        if dry_run {
            info!(would_move = %src.display(), to = %dst.display(), "[dry-run]");
        } else {
            fs::rename(src, &dst)
                .with_context(|| format!("moving {} → {}", src.display(), dst.display()))?;
            info!(moved = %src.display(), to = %dst.display(), "moved file");
        }
        moved_any = true;
    }
    if dry_run {
        info!(would_rmdir = %pseudo.display(), "[dry-run]");
    } else if moved_any && fs::read_dir(pseudo)?.flatten().next().is_none() {
        fs::remove_dir(pseudo).with_context(|| format!("rmdir {}", pseudo.display()))?;
        info!(removed = %pseudo.display(), "removed empty pseudo-folder");
    }
    Ok(())
}

fn run_remove_superseded(root: &Path, dry_run: bool) -> Result<()> {
    let mut slots: HashMap<(String, u32), Vec<(PathBuf, ParsedFile)>> = HashMap::new();
    for entry in WalkDir::new(root).follow_links(false) {
        let Ok(entry) = entry else { continue };
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.into_path();
        // Don't loop over previously-replaced files.
        if path.components().any(|c| c.as_os_str() == REPLACED_DIRNAME) {
            continue;
        }
        if !is_video(&path) {
            continue;
        }
        let Some(parsed) = ParsedFile::from_path(&path) else {
            continue;
        };
        let key = (normalize_arc(&parsed.arc), parsed.episode);
        slots.entry(key).or_default().push((path, parsed));
    }

    let replaced_dir = root.join(REPLACED_DIRNAME);
    let mut moved = 0usize;
    let mut errored = 0usize;
    for files in slots.values() {
        let has_ext = files.iter().any(|(_, p)| p.extended);
        let has_reg = files.iter().any(|(_, p)| !p.extended);
        if !(has_ext && has_reg) {
            continue;
        }
        for (path, parsed) in files {
            if parsed.extended {
                continue;
            }
            if !dry_run
                && !replaced_dir.exists()
                && let Err(e) = fs::create_dir_all(&replaced_dir)
            {
                warn!(error = %e, "failed creating {}", replaced_dir.display());
                errored += 1;
                continue;
            }
            match move_to_replaced(path, &replaced_dir, dry_run) {
                Ok(()) => moved += 1,
                Err(e) => {
                    warn!(error = %e, "failed moving {}", path.display());
                    errored += 1;
                }
            }
        }
    }
    info!(
        moved,
        errored,
        slots_checked = slots.len(),
        "remove-superseded complete (regulars moved to {}; review and delete when comfortable)",
        replaced_dir.display(),
    );
    Ok(())
}

fn move_to_replaced(src: &Path, replaced_dir: &Path, dry_run: bool) -> Result<()> {
    let name = src.file_name().context("source has no filename")?;
    let dst = replaced_dir.join(name);
    if dst.exists() {
        warn!(dst = %dst.display(), src = %src.display(), "destination exists; skipping");
        return Ok(());
    }
    if dry_run {
        info!(would_move = %src.display(), to = %dst.display(), "[dry-run]");
    } else {
        fs::rename(src, &dst)
            .with_context(|| format!("moving {} → {}", src.display(), dst.display()))?;
        info!(moved = %src.display(), to = %dst.display(), "moved superseded file");
    }
    // Move sidecar .nfo too if present.
    let nfo = src.with_extension("nfo");
    if nfo.exists()
        && let Some(nfo_name) = nfo.file_name()
    {
        let nfo_dst = replaced_dir.join(nfo_name);
        if !nfo_dst.exists() {
            if dry_run {
                info!(would_move = %nfo.display(), to = %nfo_dst.display(), "[dry-run]");
            } else {
                fs::rename(&nfo, &nfo_dst)
                    .with_context(|| format!("moving {} → {}", nfo.display(), nfo_dst.display()))?;
            }
        }
    }
    Ok(())
}

fn collect_arc_dirs(root: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for entry in fs::read_dir(root).with_context(|| format!("reading {}", root.display()))? {
        let entry = entry?;
        let path = entry.path();
        let ft = entry.file_type()?;
        if !ft.is_dir() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if !is_arc_folder_name(name) {
            continue;
        }
        out.push(path);
    }
    // Sort by the chapter range's leading number so triple-digit ranges
    // (`[1058-]`) don't lex-sort between `[1-7]` and `[2-3]`.
    out.sort_by(|a, b| {
        let ka = a.file_name().and_then(|n| n.to_str()).map(arc_chapter_key);
        let kb = b.file_name().and_then(|n| n.to_str()).map(arc_chapter_key);
        ka.cmp(&kb).then_with(|| a.cmp(b))
    });
    Ok(out)
}

/// First numeric run inside the chapter-range brackets:
/// `[One Pace][1058-] Egghead [...]` → 1058. Returns 0 if no leading digits.
fn arc_chapter_key(name: &str) -> u32 {
    let after_first_bracket = name.split_once(']').map(|x| x.1).unwrap_or("");
    let digits: String = after_first_bracket
        .chars()
        .skip_while(|c| !c.is_ascii_digit())
        .take_while(|c| c.is_ascii_digit())
        .collect();
    digits.parse().unwrap_or(0)
}

pub(crate) fn classify(dir: &Path) -> Plan {
    // Single pass: count entries and look for any of our marked NFOs.
    let entries = match fs::read_dir(dir) {
        Ok(it) => it,
        Err(_) => return Plan::Leave(dir.to_path_buf(), "unreadable"),
    };
    let mut total = 0usize;
    let mut has_our_nfo = false;
    for entry in entries.flatten() {
        total += 1;
        if has_our_nfo {
            continue;
        }
        let path = entry.path();
        let is_nfo = path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|ext| ext.eq_ignore_ascii_case("nfo"));
        if !is_nfo {
            continue;
        }
        match writer::marker_status(&path) {
            MarkerStatus::IntactOurs | MarkerStatus::EditedOurs => has_our_nfo = true,
            MarkerStatus::Absent => {}
        }
    }
    if has_our_nfo {
        return Plan::Leave(dir.to_path_buf(), "matched");
    }
    if total == 0 {
        Plan::Rmdir(dir.to_path_buf())
    } else {
        Plan::WriteIgnore(dir.to_path_buf())
    }
}

#[derive(Debug, PartialEq, Eq)]
enum Outcome {
    Removed,
    WroteIgnore,
    LeftMatched,
    LeftOther,
}

fn apply(plan: Plan, dry_run: bool) -> Result<Outcome> {
    match plan {
        Plan::Rmdir(path) => {
            if dry_run {
                info!(would_rmdir = %path.display(), "[dry-run]");
                return Ok(Outcome::Removed);
            }
            fs::remove_dir(&path)
                .with_context(|| format!("rmdir {} (non-empty?)", path.display()))?;
            info!(path = %path.display(), "removed empty arc folder");
            Ok(Outcome::Removed)
        }
        Plan::WriteIgnore(dir) => {
            let path = dir.join(IGNORE_FILENAME);
            if dry_run {
                info!(would_write = %path.display(), "[dry-run] .ignore");
                return Ok(Outcome::WroteIgnore);
            }
            fs::write(&path, IGNORE_BODY).with_context(|| format!("writing {}", path.display()))?;
            info!(path = %path.display(), "wrote .ignore");
            Ok(Outcome::WroteIgnore)
        }
        Plan::Leave(path, reason) => {
            info!(path = %path.display(), reason, "leaving alone");
            if reason == "matched" {
                Ok(Outcome::LeftMatched)
            } else {
                Ok(Outcome::LeftOther)
            }
        }
    }
}

fn is_our_ignore(path: &Path) -> bool {
    let Ok(content) = fs::read_to_string(path) else {
        return false;
    };
    content
        .lines()
        .next()
        .is_some_and(|line| line.starts_with(IGNORE_MARKER))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{NamedSeason, Series};
    use tempfile::tempdir;

    const ARC_NAME: &str = "[One Pace][1-7] Romance Dawn [1080p]";

    fn sample_series() -> Series {
        Series {
            title: "One Pace".into(),
            showtitle: "One Pace".into(),
            original_title: Some("One Piece".into()),
            plot: "Fan recut.".into(),
            display_order: None,
            named_seasons: vec![NamedSeason {
                number: 1,
                name: "1. Romance Dawn".into(),
            }],
        }
    }

    fn make_arc(root: &Path, name: &str) -> PathBuf {
        let p = root.join(name);
        fs::create_dir_all(&p).unwrap();
        p
    }

    #[test]
    fn classify_empty_arc_dir_to_rmdir() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        assert_eq!(classify(&arc), Plan::Rmdir(arc));
    }

    #[test]
    fn classify_foreign_nfo_only_to_ignore() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        // Foreign NFO without our marker.
        fs::write(
            arc.join("season.nfo"),
            "<?xml version=\"1.0\"?>\n<season><title>foreign</title></season>\n",
        )
        .unwrap();
        assert_eq!(classify(&arc), Plan::WriteIgnore(arc));
    }

    #[test]
    fn classify_matched_arc_to_leave() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        writer::write_series(&arc.join("tvshow.nfo"), &sample_series(), false).unwrap();
        assert_eq!(classify(&arc), Plan::Leave(arc, "matched"));
    }

    #[test]
    fn classify_edited_ours_still_counts_as_matched() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        let nfo = arc.join("tvshow.nfo");
        writer::write_series(&nfo, &sample_series(), false).unwrap();
        // Tamper so marker_status returns EditedOurs.
        let mut content = fs::read_to_string(&nfo).unwrap();
        content.push_str("<!-- user edit -->\n");
        fs::write(&nfo, content).unwrap();
        assert_eq!(classify(&arc), Plan::Leave(arc, "matched"));
    }

    #[test]
    fn classify_hidden_entry_counts_as_non_empty() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        fs::write(arc.join(".DS_Store"), b"junk").unwrap();
        assert_eq!(classify(&arc), Plan::WriteIgnore(arc));
    }

    #[test]
    fn remove_only_touches_marked_ignore_files() {
        let dir = tempdir().unwrap();
        let ours = make_arc(dir.path(), ARC_NAME);
        let theirs = make_arc(dir.path(), "[One Pace][8-21] Orange Town [1080p]");
        fs::write(ours.join(IGNORE_FILENAME), IGNORE_BODY).unwrap();
        fs::write(theirs.join(IGNORE_FILENAME), "# user wrote this\n").unwrap();

        run(
            dir.path(),
            Options {
                dry_run: false,
                remove: true,
                remove_superseded: false,
                migrate_extended_folders: false,
            },
        )
        .unwrap();

        assert!(
            !ours.join(IGNORE_FILENAME).exists(),
            "ours should be removed"
        );
        assert!(
            theirs.join(IGNORE_FILENAME).exists(),
            "foreign should remain"
        );
    }

    #[test]
    fn rmdir_refuses_non_empty() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        // Force a Rmdir plan but with a file present — apply should error.
        fs::write(arc.join("surprise.txt"), b"x").unwrap();
        let err = apply(Plan::Rmdir(arc.clone()), false).unwrap_err();
        assert!(
            format!("{err:#}").contains("rmdir"),
            "expected rmdir error, got {err:#}"
        );
        // The folder and its contents are still there.
        assert!(arc.exists());
        assert!(arc.join("surprise.txt").exists());
    }

    #[test]
    fn dry_run_writes_nothing() {
        let dir = tempdir().unwrap();
        // One empty arc (would rmdir) and one with foreign NFO (would ignore).
        let empty = make_arc(dir.path(), ARC_NAME);
        let foreign = make_arc(dir.path(), "[One Pace][8-21] Orange Town [1080p]");
        fs::write(foreign.join("season.nfo"), "<foreign/>\n").unwrap();

        run(
            dir.path(),
            Options {
                dry_run: true,
                remove: false,
                remove_superseded: false,
                migrate_extended_folders: false,
            },
        )
        .unwrap();

        // Nothing was removed, nothing was written.
        assert!(empty.exists(), "empty arc should still exist after dry-run");
        assert!(foreign.exists());
        assert!(
            !foreign.join(IGNORE_FILENAME).exists(),
            "no .ignore should be written"
        );
        assert!(foreign.join("season.nfo").exists(), "foreign NFO untouched");
    }

    #[test]
    fn ignores_non_arc_directories() {
        let dir = tempdir().unwrap();
        // Looks like a series wrapper, not an arc.
        make_arc(dir.path(), "Season 1");
        let arc = make_arc(dir.path(), ARC_NAME);

        run(
            dir.path(),
            Options {
                dry_run: false,
                remove: false,
                remove_superseded: false,
                migrate_extended_folders: false,
            },
        )
        .unwrap();

        // Non-arc dir untouched, empty arc removed.
        assert!(dir.path().join("Season 1").exists());
        assert!(!arc.exists());
    }

    #[test]
    fn arc_chapter_key_extracts_leading_number() {
        assert_eq!(arc_chapter_key("[One Pace][1058-] Egghead [720p]"), 1058,);
        assert_eq!(arc_chapter_key("[One Pace][1-7] Romance Dawn [1080p]"), 1);
        assert_eq!(arc_chapter_key("[One Pace][42,22] Gaimon [1080p]"), 42);
        assert_eq!(arc_chapter_key("no brackets"), 0);
    }

    #[test]
    fn collect_arc_dirs_sorts_numerically_not_lexically() {
        // Bug-fix regression: lex sort would put [1058-] between [1-7] and [2-3].
        let dir = tempdir().unwrap();
        make_arc(dir.path(), "[One Pace][1058-] Egghead [720p]");
        make_arc(dir.path(), "[One Pace][2-3] Orange Town [1080p]");
        make_arc(dir.path(), "[One Pace][1-7] Romance Dawn [1080p]");

        let dirs = collect_arc_dirs(dir.path()).unwrap();
        let names: Vec<&str> = dirs
            .iter()
            .map(|p| p.file_name().unwrap().to_str().unwrap())
            .collect();
        assert_eq!(
            names,
            vec![
                "[One Pace][1-7] Romance Dawn [1080p]",
                "[One Pace][2-3] Orange Town [1080p]",
                "[One Pace][1058-] Egghead [720p]",
            ],
        );
    }

    fn touch(path: &Path) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, b"x").unwrap();
    }

    #[test]
    fn migrate_extended_folders_moves_into_parent_arc() {
        let root = tempdir().unwrap();
        // Real arc folder exists.
        let arc = make_arc(root.path(), "[One Pace][79-81] Arlong Park [1080p]");
        // Per-cut pseudo-folder with an Extended .mkv + sidecar .nfo.
        let pseudo = make_arc(root.path(), "[One Pace] Arlong Park 05 Extended");
        let mkv = pseudo.join("[One Pace][79-81] Arlong Park 05 Extended [1080p][ACD6AA5F].mkv");
        let nfo = pseudo.join("[One Pace][79-81] Arlong Park 05 Extended [1080p][ACD6AA5F].nfo");
        touch(&mkv);
        touch(&nfo);

        run(
            root.path(),
            Options {
                dry_run: false,
                remove: false,
                remove_superseded: false,
                migrate_extended_folders: true,
            },
        )
        .unwrap();

        // Files moved into arc folder; pseudo-folder gone.
        assert!(arc.join(mkv.file_name().unwrap()).exists());
        assert!(arc.join(nfo.file_name().unwrap()).exists());
        assert!(!pseudo.exists());
    }

    #[test]
    fn migrate_extended_folders_skips_when_no_parent_arc() {
        let root = tempdir().unwrap();
        // No parent arc folder for "Egghead" — should skip with warn.
        let pseudo = make_arc(root.path(), "[One Pace] Egghead 13 Extended");
        let mkv = pseudo.join("[One Pace][1079] Egghead 13 Extended [1080p][88019227].mkv");
        touch(&mkv);

        run(
            root.path(),
            Options {
                dry_run: false,
                remove: false,
                remove_superseded: false,
                migrate_extended_folders: true,
            },
        )
        .unwrap();

        // Pseudo-folder + file untouched.
        assert!(pseudo.exists());
        assert!(mkv.exists());
    }

    #[test]
    fn remove_superseded_moves_regular_when_extended_exists() {
        let root = tempdir().unwrap();
        let arc = make_arc(root.path(), "[One Pace][79-81] Arlong Park [1080p]");
        let reg = arc.join("[One Pace][79-81] Arlong Park 05 [1080p][AAAAAAAA].mkv");
        let reg_nfo = reg.with_extension("nfo");
        let ext = arc.join("[One Pace][79-81] Arlong Park 05 Extended [1080p][BBBBBBBB].mkv");
        touch(&reg);
        touch(&reg_nfo);
        touch(&ext);

        run(
            root.path(),
            Options {
                dry_run: false,
                remove: false,
                remove_superseded: true,
                migrate_extended_folders: false,
            },
        )
        .unwrap();

        // Regular + sidecar moved to _replaced/, Extended stays.
        assert!(!reg.exists());
        assert!(!reg_nfo.exists());
        assert!(ext.exists());
        let replaced = root.path().join(REPLACED_DIRNAME);
        assert!(replaced.join(reg.file_name().unwrap()).exists());
        assert!(replaced.join(reg_nfo.file_name().unwrap()).exists());
    }

    #[test]
    fn remove_superseded_leaves_unpaired_regular_alone() {
        let root = tempdir().unwrap();
        let arc = make_arc(root.path(), "[One Pace][1-7] Romance Dawn [1080p]");
        let reg = arc.join("[One Pace][1] Romance Dawn 01 [1080p][AAAAAAAA].mkv");
        touch(&reg);

        run(
            root.path(),
            Options {
                dry_run: false,
                remove: false,
                remove_superseded: true,
                migrate_extended_folders: false,
            },
        )
        .unwrap();

        assert!(
            reg.exists(),
            "regular without Extended counterpart untouched"
        );
        assert!(!root.path().join(REPLACED_DIRNAME).exists());
    }

    #[test]
    fn remove_superseded_dry_run_writes_nothing() {
        let root = tempdir().unwrap();
        let arc = make_arc(root.path(), "[One Pace][79-81] Arlong Park [1080p]");
        let reg = arc.join("[One Pace][79-81] Arlong Park 05 [1080p][AAAAAAAA].mkv");
        let ext = arc.join("[One Pace][79-81] Arlong Park 05 Extended [1080p][BBBBBBBB].mkv");
        touch(&reg);
        touch(&ext);

        run(
            root.path(),
            Options {
                dry_run: true,
                remove: false,
                remove_superseded: true,
                migrate_extended_folders: false,
            },
        )
        .unwrap();

        assert!(reg.exists());
        assert!(ext.exists());
        assert!(!root.path().join(REPLACED_DIRNAME).exists());
    }

    #[test]
    fn apply_writes_ignore_with_marker() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        fs::write(arc.join("foreign.nfo"), "<foreign/>\n").unwrap();

        apply(Plan::WriteIgnore(arc.clone()), false).unwrap();
        let content = fs::read_to_string(arc.join(IGNORE_FILENAME)).unwrap();
        assert!(content.starts_with(IGNORE_MARKER));
    }
}
