//! `cleanup` subcommand: tidy up orphan arc folders left behind by other
//! tagging tools or by earlier matched-then-renamed pacefinder runs.
//!
//! Walks the immediate children of `<series-root>`. For each entry that
//! looks like an arc folder (per [`is_arc_folder_name`]) and does *not*
//! contain a pacefinder-managed `.nfo`:
//!
//! - empty folder → `rmdir`,
//! - non-empty folder → drop a small `.ignore` file so Jellyfin stops
//!   treating it as a season.
//!
//! Arc folders that hold at least one pacefinder-marked `.nfo` are left
//! alone — they're part of an active library. Foreign content lives
//! untouched; we only ever add `.ignore`, never delete media.
//!
//! Reverse with `--remove`, which deletes only the `.ignore` files whose
//! first line is `# generated by pacefinder`. User-authored `.ignore`
//! files are preserved.

use anyhow::{Context, Result, anyhow};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use tracing::{info, warn};

use crate::matcher::is_arc_folder_name;
use crate::nfo::writer::{self, MarkerStatus};

/// First line of any `.ignore` we write. `--remove` keys on this prefix.
const IGNORE_MARKER: &str = "# generated by pacefinder";
const IGNORE_BODY: &str = "# generated by pacefinder\n\
                           # delete this file to make Jellyfin scan this folder again\n";
const IGNORE_FILENAME: &str = ".ignore";

pub struct Options {
    pub dry_run: bool,
    pub remove: bool,
}

#[derive(Debug, PartialEq, Eq)]
pub(crate) enum Plan {
    Rmdir(PathBuf),
    WriteIgnore(PathBuf),
    Leave(PathBuf, &'static str),
}

pub fn run(root: &Path, opts: Options) -> Result<()> {
    let root = canonicalize_or_helpful_error(root)?;
    info!(
        path = %root.display(),
        dry_run = opts.dry_run,
        remove = opts.remove,
        "cleaning up arc folders",
    );

    if opts.remove {
        return run_remove(&root, opts.dry_run);
    }

    let arc_dirs = collect_arc_dirs(&root)?;
    let mut removed_dirs = 0usize;
    let mut wrote_ignore = 0usize;
    let mut left_matched = 0usize;
    let mut left_other = 0usize;
    let mut errored = 0usize;

    for dir in &arc_dirs {
        let plan = classify(dir);
        match apply(plan, opts.dry_run) {
            Ok(Outcome::Removed) => removed_dirs += 1,
            Ok(Outcome::WroteIgnore) => wrote_ignore += 1,
            Ok(Outcome::LeftMatched) => left_matched += 1,
            Ok(Outcome::LeftOther) => left_other += 1,
            Err(e) => {
                warn!(error = %e, "skipping {}", dir.display());
                errored += 1;
            }
        }
    }

    info!(
        removed_dirs,
        wrote_ignore,
        left_matched,
        left_other,
        errored,
        total = arc_dirs.len(),
        "cleanup complete",
    );

    if !opts.dry_run && (removed_dirs > 0 || wrote_ignore > 0) {
        info!(
            "After applying, trigger a Jellyfin library scan. If ghost seasons \
             persist, remove + re-add the library in Jellyfin's admin UI."
        );
    }
    Ok(())
}

fn run_remove(root: &Path, dry_run: bool) -> Result<()> {
    let arc_dirs = collect_arc_dirs(root)?;
    let mut removed = 0usize;
    let mut skipped_foreign = 0usize;
    let mut errored = 0usize;
    for dir in &arc_dirs {
        let ignore_path = dir.join(IGNORE_FILENAME);
        if !ignore_path.exists() {
            continue;
        }
        if !is_our_ignore(&ignore_path) {
            warn!(
                path = %ignore_path.display(),
                "leaving foreign `.ignore` (no pacefinder marker)"
            );
            skipped_foreign += 1;
            continue;
        }
        if dry_run {
            info!(would_remove = %ignore_path.display(), "[dry-run] remove .ignore");
            removed += 1;
            continue;
        }
        match fs::remove_file(&ignore_path) {
            Ok(()) => {
                info!(path = %ignore_path.display(), "removed .ignore");
                removed += 1;
            }
            Err(e) => {
                warn!(error = %e, "failed to remove {}", ignore_path.display());
                errored += 1;
            }
        }
    }
    info!(
        removed,
        skipped_foreign,
        errored,
        total = arc_dirs.len(),
        "cleanup --remove complete",
    );
    Ok(())
}

fn canonicalize_or_helpful_error(root: &Path) -> Result<PathBuf> {
    root.canonicalize().map_err(|e| {
        if e.kind() == io::ErrorKind::NotFound {
            anyhow!("path does not exist: {}", root.display())
        } else {
            anyhow!("{}: {}", root.display(), e)
        }
    })
}

fn collect_arc_dirs(root: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for entry in fs::read_dir(root).with_context(|| format!("reading {}", root.display()))? {
        let entry = entry?;
        let path = entry.path();
        let ft = entry.file_type()?;
        if !ft.is_dir() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if !is_arc_folder_name(name) {
            continue;
        }
        out.push(path);
    }
    out.sort();
    Ok(out)
}

pub(crate) fn classify(dir: &Path) -> Plan {
    // Single pass: count entries and look for any of our marked NFOs.
    let entries = match fs::read_dir(dir) {
        Ok(it) => it,
        Err(_) => return Plan::Leave(dir.to_path_buf(), "unreadable"),
    };
    let mut total = 0usize;
    let mut has_our_nfo = false;
    for entry in entries.flatten() {
        total += 1;
        if has_our_nfo {
            continue;
        }
        let path = entry.path();
        let is_nfo = path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|ext| ext.eq_ignore_ascii_case("nfo"));
        if !is_nfo {
            continue;
        }
        match writer::marker_status(&path) {
            MarkerStatus::IntactOurs | MarkerStatus::EditedOurs => has_our_nfo = true,
            MarkerStatus::Absent => {}
        }
    }
    if has_our_nfo {
        return Plan::Leave(dir.to_path_buf(), "matched");
    }
    if total == 0 {
        Plan::Rmdir(dir.to_path_buf())
    } else {
        Plan::WriteIgnore(dir.to_path_buf())
    }
}

#[derive(Debug, PartialEq, Eq)]
enum Outcome {
    Removed,
    WroteIgnore,
    LeftMatched,
    LeftOther,
}

fn apply(plan: Plan, dry_run: bool) -> Result<Outcome> {
    match plan {
        Plan::Rmdir(path) => {
            if dry_run {
                info!(would_rmdir = %path.display(), "[dry-run]");
                return Ok(Outcome::Removed);
            }
            fs::remove_dir(&path)
                .with_context(|| format!("rmdir {} (non-empty?)", path.display()))?;
            info!(path = %path.display(), "removed empty arc folder");
            Ok(Outcome::Removed)
        }
        Plan::WriteIgnore(dir) => {
            let path = dir.join(IGNORE_FILENAME);
            if dry_run {
                info!(would_write = %path.display(), "[dry-run] .ignore");
                return Ok(Outcome::WroteIgnore);
            }
            fs::write(&path, IGNORE_BODY).with_context(|| format!("writing {}", path.display()))?;
            info!(path = %path.display(), "wrote .ignore");
            Ok(Outcome::WroteIgnore)
        }
        Plan::Leave(path, reason) => {
            info!(path = %path.display(), reason, "leaving alone");
            if reason == "matched" {
                Ok(Outcome::LeftMatched)
            } else {
                Ok(Outcome::LeftOther)
            }
        }
    }
}

fn is_our_ignore(path: &Path) -> bool {
    let Ok(content) = fs::read_to_string(path) else {
        return false;
    };
    content
        .lines()
        .next()
        .is_some_and(|line| line.starts_with(IGNORE_MARKER))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{NamedSeason, Series};
    use tempfile::tempdir;

    const ARC_NAME: &str = "[One Pace][1-7] Romance Dawn [1080p]";

    fn sample_series() -> Series {
        Series {
            title: "One Pace".into(),
            showtitle: "One Pace".into(),
            original_title: Some("One Piece".into()),
            plot: "Fan recut.".into(),
            named_seasons: vec![NamedSeason {
                number: 1,
                name: "1. Romance Dawn".into(),
            }],
        }
    }

    fn make_arc(root: &Path, name: &str) -> PathBuf {
        let p = root.join(name);
        fs::create_dir_all(&p).unwrap();
        p
    }

    #[test]
    fn classify_empty_arc_dir_to_rmdir() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        assert_eq!(classify(&arc), Plan::Rmdir(arc));
    }

    #[test]
    fn classify_foreign_nfo_only_to_ignore() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        // Foreign NFO without our marker.
        fs::write(
            arc.join("season.nfo"),
            "<?xml version=\"1.0\"?>\n<season><title>foreign</title></season>\n",
        )
        .unwrap();
        assert_eq!(classify(&arc), Plan::WriteIgnore(arc));
    }

    #[test]
    fn classify_matched_arc_to_leave() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        writer::write_series(&arc.join("tvshow.nfo"), &sample_series()).unwrap();
        assert_eq!(classify(&arc), Plan::Leave(arc, "matched"));
    }

    #[test]
    fn classify_edited_ours_still_counts_as_matched() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        let nfo = arc.join("tvshow.nfo");
        writer::write_series(&nfo, &sample_series()).unwrap();
        // Tamper so marker_status returns EditedOurs.
        let mut content = fs::read_to_string(&nfo).unwrap();
        content.push_str("<!-- user edit -->\n");
        fs::write(&nfo, content).unwrap();
        assert_eq!(classify(&arc), Plan::Leave(arc, "matched"));
    }

    #[test]
    fn classify_hidden_entry_counts_as_non_empty() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        fs::write(arc.join(".DS_Store"), b"junk").unwrap();
        assert_eq!(classify(&arc), Plan::WriteIgnore(arc));
    }

    #[test]
    fn remove_only_touches_marked_ignore_files() {
        let dir = tempdir().unwrap();
        let ours = make_arc(dir.path(), ARC_NAME);
        let theirs = make_arc(dir.path(), "[One Pace][8-21] Orange Town [1080p]");
        fs::write(ours.join(IGNORE_FILENAME), IGNORE_BODY).unwrap();
        fs::write(theirs.join(IGNORE_FILENAME), "# user wrote this\n").unwrap();

        run(
            dir.path(),
            Options {
                dry_run: false,
                remove: true,
            },
        )
        .unwrap();

        assert!(
            !ours.join(IGNORE_FILENAME).exists(),
            "ours should be removed"
        );
        assert!(
            theirs.join(IGNORE_FILENAME).exists(),
            "foreign should remain"
        );
    }

    #[test]
    fn rmdir_refuses_non_empty() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        // Force a Rmdir plan but with a file present — apply should error.
        fs::write(arc.join("surprise.txt"), b"x").unwrap();
        let err = apply(Plan::Rmdir(arc.clone()), false).unwrap_err();
        assert!(
            format!("{err:#}").contains("rmdir"),
            "expected rmdir error, got {err:#}"
        );
        // The folder and its contents are still there.
        assert!(arc.exists());
        assert!(arc.join("surprise.txt").exists());
    }

    #[test]
    fn dry_run_writes_nothing() {
        let dir = tempdir().unwrap();
        // One empty arc (would rmdir) and one with foreign NFO (would ignore).
        let empty = make_arc(dir.path(), ARC_NAME);
        let foreign = make_arc(dir.path(), "[One Pace][8-21] Orange Town [1080p]");
        fs::write(foreign.join("season.nfo"), "<foreign/>\n").unwrap();

        run(
            dir.path(),
            Options {
                dry_run: true,
                remove: false,
            },
        )
        .unwrap();

        // Nothing was removed, nothing was written.
        assert!(empty.exists(), "empty arc should still exist after dry-run");
        assert!(foreign.exists());
        assert!(
            !foreign.join(IGNORE_FILENAME).exists(),
            "no .ignore should be written"
        );
        assert!(foreign.join("season.nfo").exists(), "foreign NFO untouched");
    }

    #[test]
    fn ignores_non_arc_directories() {
        let dir = tempdir().unwrap();
        // Looks like a series wrapper, not an arc.
        make_arc(dir.path(), "Season 1");
        let arc = make_arc(dir.path(), ARC_NAME);

        run(
            dir.path(),
            Options {
                dry_run: false,
                remove: false,
            },
        )
        .unwrap();

        // Non-arc dir untouched, empty arc removed.
        assert!(dir.path().join("Season 1").exists());
        assert!(!arc.exists());
    }

    #[test]
    fn apply_writes_ignore_with_marker() {
        let dir = tempdir().unwrap();
        let arc = make_arc(dir.path(), ARC_NAME);
        fs::write(arc.join("foreign.nfo"), "<foreign/>\n").unwrap();

        apply(Plan::WriteIgnore(arc.clone()), false).unwrap();
        let content = fs::read_to_string(arc.join(IGNORE_FILENAME)).unwrap();
        assert!(content.starts_with(IGNORE_MARKER));
    }
}
