use clap::{Parser, Subcommand, ValueEnum};
use std::path::PathBuf;
use std::time::Duration;

#[derive(Parser, Debug)]
#[command(
    name = "pacefinder",
    version,
    about = "Generate Kodi-format NFOs and artwork for a One Pace media library"
)]
pub struct Cli {
    /// Increase verbosity: -v debug, -vv trace. Conflicts with --quiet.
    #[arg(short, long, global = true, action = clap::ArgAction::Count)]
    pub verbose: u8,

    /// Suppress output: -q warn only, -qq error only, -qqq silent.
    /// Conflicts with --verbose.
    #[arg(
        short,
        long,
        global = true,
        action = clap::ArgAction::Count,
        conflicts_with = "verbose"
    )]
    pub quiet: u8,

    /// Power-user escape hatch: tracing-subscriber env filter string.
    /// Overrides --verbose/--quiet. Also reads `PACEFINDER_LOG`.
    #[arg(long, global = true, env = "PACEFINDER_LOG")]
    pub log: Option<String>,

    #[command(subcommand)]
    pub command: Command,
}

// Order here is the order in `--help`. Primary command first, then
// diagnostic, then one-time setup, then utilities.
#[derive(Subcommand, Debug)]
pub enum Command {
    /// Generate NFO sidecars for every recognized One Pace file under <path>
    Generate {
        /// Root of the One Pace series folder (one level above the arc folders).
        path: PathBuf,

        /// Resolve and log writes without touching the filesystem.
        #[arg(long)]
        dry_run: bool,

        /// Cache TTL for upstream metadata fetches (humantime: 7d, 24h, 30m).
        #[arg(long, default_value = "7d", value_parser = parse_humantime)]
        cache_ttl: Duration,

        /// Bypass the on-disk HTTP cache.
        #[arg(long)]
        refresh: bool,

        /// Overwrite conflicting files (foreign / user-edited / changed posters)
        /// without prompting.
        #[arg(long)]
        force: bool,

        /// Don't prompt — skip conflicts silently. Use in scripts/CI.
        /// Mutually exclusive with --force.
        #[arg(long, conflicts_with = "force")]
        non_interactive: bool,

        /// `<displayorder>` written into tvshow.nfo. Jellyfin/Kodi use it
        /// to lay out episodes in the series view. Defaults to `absolute`
        /// (flat 1..N list across arcs — the right view for a re-edit
        /// like One Pace); pass `aired` for the season-card grouping or
        /// `dvd` for DVD order.
        #[arg(long, value_enum, default_value_t = DisplayOrder::Absolute)]
        display_order: DisplayOrder,

        /// Emit `<lockdata>true</lockdata>` so Jellyfin's metadata explorer
        /// stops overwriting our NFOs. `none` (default) — opt into locking
        /// once you've verified the metadata is correct. `show` locks
        /// tvshow.nfo only; `all` also locks season.nfo and episode.nfo.
        /// Heads-up: Jellyfin copies the lock state into its DB on scan
        /// and then ignores future NFO changes for locked items — see
        /// docs/troubleshooting.md before using `all`.
        #[arg(long, value_enum, default_value_t = LockMode::None)]
        lock: LockMode,
    },
    /// Walk a media directory and report what was recognized
    Scan {
        /// Root of the One Pace library to scan.
        path: PathBuf,
    },
    /// Wrap top-level arc folders inside a series folder
    Reorder {
        /// Library root containing the arc folders.
        path: PathBuf,

        /// Name of the series wrapper folder.
        #[arg(long, default_value = "One Pace")]
        series_folder: String,

        /// Resolve and log moves without touching the filesystem.
        #[arg(long)]
        dry_run: bool,
    },
    /// Tidy up orphan arc folders left behind by foreign tools or earlier runs.
    /// Removes empty arc folders and writes `.ignore` into ones that only hold
    /// non-pacefinder content (so Jellyfin stops surfacing them as ghost
    /// seasons). Arc folders that already contain a pacefinder-managed `.nfo`
    /// are left untouched.
    Cleanup {
        /// Series-root containing arc folders.
        path: PathBuf,

        /// Resolve and log actions without touching the filesystem. Default off
        /// (matches the rest of the CLI — explicit safety via classification, not
        /// dry-run-first).
        #[arg(long)]
        dry_run: bool,

        /// Reverse a previous run: delete pacefinder-written `.ignore` files
        /// (those whose first line starts with `# generated by pacefinder`).
        /// Empty directories aren't recreated.
        #[arg(long, conflicts_with = "dry_run")]
        remove: bool,

        /// Move regular cuts aside when an Extended cut for the same
        /// (arc, episode) is present in the library. Destination is
        /// `<series-root>/_replaced/` (reversible — review and delete
        /// when you're sure).
        #[arg(long)]
        remove_superseded: bool,

        /// Move Extended `.mkv` files out of per-cut pseudo-folders
        /// (`[One Pace] <Arc> <N> Extended/`) into the matching parent
        /// arc folder. `rmdir`s the now-empty pseudo-folder.
        #[arg(long)]
        migrate_extended_folders: bool,
    },
    /// Queue missing releases for download via a torrent client (qBittorrent).
    /// Diffs the upstream /releases page against your library + the client's
    /// current queue, adds each missing magnet with `save_path` set to the
    /// matching arc folder. Queue-and-go — no waiting, no progress bars.
    Download {
        /// Series-root for the library (same as `generate`). Arc folders
        /// live here; new downloads land in `<library>/<arc-folder>/`.
        path: PathBuf,

        /// qBittorrent Web UI URL. Env: `PACEFINDER_QBT_URL`.
        #[arg(
            long,
            env = "PACEFINDER_QBT_URL",
            default_value = "http://localhost:8080"
        )]
        qbt_url: String,

        /// qBittorrent username. Env: `PACEFINDER_QBT_USER`.
        #[arg(long, env = "PACEFINDER_QBT_USER", default_value = "admin")]
        qbt_user: String,

        /// qBittorrent password. Prefer the env var to keep it out of
        /// shell history. Env: `PACEFINDER_QBT_PASS`.
        #[arg(long, env = "PACEFINDER_QBT_PASS", default_value = "adminadmin")]
        qbt_pass: String,

        /// Optional qBittorrent category to tag queued torrents with.
        #[arg(long)]
        qbt_category: Option<String>,

        /// Max acceptable vertical resolution. Releases above this are
        /// skipped; below = accepted (best available ≤ this).
        #[arg(long, default_value = "1080p")]
        resolution: String,

        /// Cache TTL for the /releases fetch (humantime: 7d, 24h, 30m).
        #[arg(long, default_value = "1h", value_parser = parse_humantime)]
        cache_ttl: Duration,

        /// Bypass the on-disk HTTP cache when fetching /releases.
        #[arg(long)]
        refresh: bool,

        /// Resolve and log actions without authenticating to qBittorrent
        /// or queueing anything.
        #[arg(long)]
        dry_run: bool,

        /// Pre-populate an `episode.nfo` next to each queued torrent's
        /// target path. When the .mkv arrives, Jellyfin picks it up with
        /// metadata already in place. Run `pacefinder generate` first
        /// for tvshow.nfo / season.nfo.
        #[arg(long)]
        prepopulate_nfo: bool,

        /// Re-queue episodes whose CRC is already in your library
        /// (treats them as if missing). Useful when upstream re-encodes
        /// and you want the new version.
        #[arg(long)]
        requeue_existing: bool,

        /// When both a regular and an Extended cut exist for the same
        /// (arc, episode) on upstream, queue the Extended (preference
        /// wins over the resolution cap). The "have" set treats regular
        /// and Extended as fungible — if you already have either, the
        /// slot is filled. Pair with `pacefinder cleanup
        /// --remove-superseded` afterwards to move stranded regulars
        /// out of the way. Env: `PACEFINDER_PREFER_EXTENDED`.
        #[arg(long, env = "PACEFINDER_PREFER_EXTENDED")]
        prefer_extended: bool,

        /// Only consider releases whose arc name contains this substring
        /// (case-insensitive). Useful for trying it out on one arc first.
        #[arg(long)]
        only_arc: Option<String>,

        /// Exit non-zero if `/releases` parses to zero magnets. Useful in
        /// CI to detect upstream parse regressions that would otherwise
        /// look like "nothing new to download".
        #[arg(long)]
        fail_on_empty: bool,

        /// Translate save paths from the host filesystem to qBittorrent's
        /// view. Format: `HOST=CONTAINER` (e.g. `/mnt/media=/downloads`).
        /// Needed when qBittorrent runs in a container or other namespace
        /// with a different mount table. Env: `PACEFINDER_SAVE_PATH_MAP`.
        #[arg(long, env = "PACEFINDER_SAVE_PATH_MAP")]
        save_path_map: Option<String>,
    },
    /// Inspect or clear the on-disk HTTP cache
    Cache {
        #[command(subcommand)]
        action: CacheAction,
    },
    /// Print version and exit
    Version,
}

#[derive(Subcommand, Debug)]
pub enum CacheAction {
    /// Print the on-disk cache location.
    Path,
    /// Delete all cached HTTP responses.
    Clear,
}

fn parse_humantime(s: &str) -> Result<Duration, String> {
    humantime::parse_duration(s).map_err(|e| format!("invalid duration `{s}`: {e}"))
}

/// Display-order values Kodi/Jellyfin recognize for series.
#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum DisplayOrder {
    Absolute,
    Aired,
    Dvd,
}

impl DisplayOrder {
    pub fn as_kodi(self) -> &'static str {
        match self {
            Self::Absolute => "absolute",
            Self::Aired => "aired",
            Self::Dvd => "dvd",
        }
    }
}

/// Which NFO kinds carry `<lockdata>true</lockdata>`.
#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum LockMode {
    /// Don't lock anything; Jellyfin remains free to rewrite NFOs.
    None,
    /// Lock tvshow.nfo only. Season/episode NFOs stay mutable.
    Show,
    /// Lock tvshow.nfo, season.nfo, and episode.nfo.
    All,
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    #[test]
    fn display_order_as_kodi_strings() {
        assert_eq!(DisplayOrder::Absolute.as_kodi(), "absolute");
        assert_eq!(DisplayOrder::Aired.as_kodi(), "aired");
        assert_eq!(DisplayOrder::Dvd.as_kodi(), "dvd");
    }

    #[test]
    fn parse_humantime_accepts_common_forms() {
        assert_eq!(
            parse_humantime("7d").unwrap(),
            Duration::from_secs(7 * 86400)
        );
        assert_eq!(parse_humantime("30m").unwrap(), Duration::from_secs(1800));
        assert_eq!(parse_humantime("1h").unwrap(), Duration::from_secs(3600));
    }

    #[test]
    fn parse_humantime_rejects_garbage() {
        let err = parse_humantime("garbage").unwrap_err();
        assert!(err.starts_with("invalid duration"), "got: {err}");
    }

    #[test]
    fn clap_verbose_and_quiet_conflict() {
        let r = Cli::try_parse_from(["pacefinder", "-v", "-q", "scan", "/x"]);
        assert!(r.is_err(), "expected conflict between -v and -q");
    }

    #[test]
    fn clap_generate_force_and_non_interactive_conflict() {
        let r = Cli::try_parse_from([
            "pacefinder",
            "generate",
            "/x",
            "--force",
            "--non-interactive",
        ]);
        assert!(r.is_err(), "expected conflict");
    }

    #[test]
    fn clap_cleanup_dry_run_and_remove_conflict() {
        let r = Cli::try_parse_from(["pacefinder", "cleanup", "/x", "--dry-run", "--remove"]);
        assert!(r.is_err(), "expected conflict");
    }

    #[test]
    fn clap_generate_defaults() {
        let cli = Cli::try_parse_from(["pacefinder", "generate", "/x"]).unwrap();
        let Command::Generate {
            display_order,
            lock,
            cache_ttl,
            refresh,
            ..
        } = cli.command
        else {
            panic!("expected Generate");
        };
        assert!(matches!(display_order, DisplayOrder::Absolute));
        assert!(matches!(lock, LockMode::None));
        assert_eq!(cache_ttl, Duration::from_secs(7 * 86400));
        assert!(!refresh);
    }

    #[test]
    fn clap_download_defaults() {
        let cli = Cli::try_parse_from(["pacefinder", "download", "/x"]).unwrap();
        let Command::Download {
            qbt_url,
            qbt_user,
            qbt_pass,
            resolution,
            cache_ttl,
            ..
        } = cli.command
        else {
            panic!("expected Download");
        };
        assert_eq!(qbt_url, "http://localhost:8080");
        assert_eq!(qbt_user, "admin");
        assert_eq!(qbt_pass, "adminadmin");
        assert_eq!(resolution, "1080p");
        assert_eq!(cache_ttl, Duration::from_secs(3600));
    }

    #[test]
    fn clap_invalid_cache_ttl_errors_via_humantime() {
        let r = Cli::try_parse_from(["pacefinder", "generate", "/x", "--cache-ttl", "junk"]);
        assert!(r.is_err());
    }
}
