use clap::{Parser, Subcommand, ValueEnum};
use std::path::PathBuf;
use std::time::Duration;

#[derive(Parser, Debug)]
#[command(
    name = "pacefinder",
    version,
    about = "Generate Kodi-format NFOs and artwork for a One Pace media library"
)]
pub struct Cli {
    /// Increase verbosity: -v debug, -vv trace. Conflicts with --quiet.
    #[arg(short, long, global = true, action = clap::ArgAction::Count)]
    pub verbose: u8,

    /// Suppress output: -q warn only, -qq error only, -qqq silent.
    /// Conflicts with --verbose.
    #[arg(
        short,
        long,
        global = true,
        action = clap::ArgAction::Count,
        conflicts_with = "verbose"
    )]
    pub quiet: u8,

    /// Power-user escape hatch: tracing-subscriber env filter string.
    /// Overrides --verbose/--quiet. Also reads `PACEFINDER_LOG`.
    #[arg(long, global = true, env = "PACEFINDER_LOG")]
    pub log: Option<String>,

    #[command(subcommand)]
    pub command: Command,
}

// Order here is the order in `--help`. Primary command first, then
// diagnostic, then one-time setup, then utilities.
#[derive(Subcommand, Debug)]
pub enum Command {
    /// Generate NFO sidecars for every recognized One Pace file under <path>
    Generate {
        /// Root of the One Pace series folder (one level above the arc folders).
        path: PathBuf,

        /// Resolve and log writes without touching the filesystem.
        #[arg(long)]
        dry_run: bool,

        /// Cache TTL for upstream metadata fetches (humantime: 7d, 24h, 30m).
        #[arg(long, default_value = "7d", value_parser = parse_humantime)]
        cache_ttl: Duration,

        /// Bypass the on-disk HTTP cache.
        #[arg(long)]
        refresh: bool,

        /// Overwrite conflicting files (foreign / user-edited / changed posters)
        /// without prompting.
        #[arg(long)]
        force: bool,

        /// Don't prompt — skip conflicts silently. Use in scripts/CI.
        /// Mutually exclusive with --force.
        #[arg(long, conflicts_with = "force")]
        non_interactive: bool,

        /// `<displayorder>` written into tvshow.nfo. Jellyfin/Kodi use it
        /// to lay out episodes in the series view. Defaults to `absolute`
        /// (flat 1..N list across arcs — the right view for a re-edit
        /// like One Pace); pass `aired` for the season-card grouping or
        /// `dvd` for DVD order.
        #[arg(long, value_enum, default_value_t = DisplayOrder::Absolute)]
        display_order: DisplayOrder,

        /// Emit `<lockdata>true</lockdata>` so Jellyfin's metadata explorer
        /// stops overwriting our NFOs. `show` (default) locks only
        /// tvshow.nfo, `all` also locks season.nfo and episode.nfo, `none`
        /// disables locking entirely.
        #[arg(long, value_enum, default_value_t = LockMode::Show)]
        lock: LockMode,
    },
    /// Walk a media directory and report what was recognized
    Scan {
        /// Root of the One Pace library to scan.
        path: PathBuf,
    },
    /// Wrap top-level arc folders inside a series folder
    Reorder {
        /// Library root containing the arc folders.
        path: PathBuf,

        /// Name of the series wrapper folder.
        #[arg(long, default_value = "One Pace")]
        series_folder: String,

        /// Resolve and log moves without touching the filesystem.
        #[arg(long)]
        dry_run: bool,
    },
    /// Tidy up orphan arc folders left behind by foreign tools or earlier runs.
    /// Removes empty arc folders and writes `.ignore` into ones that only hold
    /// non-pacefinder content (so Jellyfin stops surfacing them as ghost
    /// seasons). Arc folders that already contain a pacefinder-managed `.nfo`
    /// are left untouched.
    Cleanup {
        /// Series-root containing arc folders.
        path: PathBuf,

        /// Resolve and log actions without touching the filesystem. Default off
        /// (matches the rest of the CLI — explicit safety via classification, not
        /// dry-run-first).
        #[arg(long)]
        dry_run: bool,

        /// Reverse a previous run: delete pacefinder-written `.ignore` files
        /// (those whose first line starts with `# generated by pacefinder`).
        /// Empty directories aren't recreated.
        #[arg(long, conflicts_with = "dry_run")]
        remove: bool,
    },
    /// Inspect or clear the on-disk HTTP cache
    Cache {
        #[command(subcommand)]
        action: CacheAction,
    },
    /// Print version and exit
    Version,
}

#[derive(Subcommand, Debug)]
pub enum CacheAction {
    /// Print the on-disk cache location.
    Path,
    /// Delete all cached HTTP responses.
    Clear,
}

fn parse_humantime(s: &str) -> Result<Duration, String> {
    humantime::parse_duration(s).map_err(|e| format!("invalid duration `{s}`: {e}"))
}

/// Display-order values Kodi/Jellyfin recognize for series.
#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum DisplayOrder {
    Absolute,
    Aired,
    Dvd,
}

impl DisplayOrder {
    pub fn as_kodi(self) -> &'static str {
        match self {
            Self::Absolute => "absolute",
            Self::Aired => "aired",
            Self::Dvd => "dvd",
        }
    }
}

/// Which NFO kinds carry `<lockdata>true</lockdata>`.
#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum LockMode {
    /// Don't lock anything; Jellyfin remains free to rewrite NFOs.
    None,
    /// Lock tvshow.nfo only. Season/episode NFOs stay mutable.
    Show,
    /// Lock tvshow.nfo, season.nfo, and episode.nfo.
    All,
}
